hello:
  docker run hello-world

podman_status:
  systemctl --user status podman.socket

build:
  docker build -t my-python-app .
 
run: build
  docker run -it --rm --name my-running-app my-python-app
